//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seating
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ph14430429082_Entities : DbContext
    {
        public ph14430429082_Entities()
            : base("name=ph14430429082_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<BreakListData_Result> BreakListData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BreakListData_Result>("BreakListData");
        }
    
        public virtual ObjectResult<DthListData_Result> DthListData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DthListData_Result>("DthListData");
        }
    
        public virtual ObjectResult<LunchListData_Result> LunchListData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LunchListData_Result>("LunchListData");
        }
    }
}
